-- ====================================================================
-- CLIMATE INTELLIGENCE FOR HEATWAVE MONITORING, PREDICTION, AND EARLY WARNING (INDIA EDITION)
-- Exact Relational Model Database Schema (Supabase PostgreSQL)
-- ====================================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Weather_Station Table
CREATE TABLE IF NOT EXISTS public."Weather_Station" (
    "Station_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Station_Code" VARCHAR(50) NOT NULL UNIQUE,
    "Station_Name" VARCHAR(255) NOT NULL,
    "Latitude" DECIMAL(10, 6) NOT NULL,
    "Longitude" DECIMAL(10, 6) NOT NULL,
    "Status" VARCHAR(50) DEFAULT 'Active' CHECK ("Status" IN ('Active', 'Maintenance', 'Inactive'))
);

-- 2. Station_Location Table
CREATE TABLE IF NOT EXISTS public."Station_Location" (
    "Station_ID" BIGINT NOT NULL REFERENCES public."Weather_Station"("Station_ID") ON DELETE CASCADE,
    "Location" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("Station_ID", "Location")
);

-- 3. Weather_Observation Table
CREATE TABLE IF NOT EXISTS public."Weather_Observation" (
    "Obs_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Station_ID" BIGINT NOT NULL REFERENCES public."Weather_Station"("Station_ID") ON DELETE CASCADE,
    "Recorded_At" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "Temperature" DECIMAL(5, 2) NOT NULL,
    "Humidity" DECIMAL(5, 2) NOT NULL,
    "Rainfall" DECIMAL(6, 2) DEFAULT 0.00 NOT NULL,
    "Wind_Speed" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL
);

-- 4. Report_Analysis Table
CREATE TABLE IF NOT EXISTS public."Report_Analysis" (
    "R_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Obs_ID" BIGINT NOT NULL REFERENCES public."Weather_Observation"("Obs_ID") ON DELETE CASCADE,
    "Report_Type" VARCHAR(100) NOT NULL,
    "Criteria" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    "Generated_At" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 5. Heatwave_Prediction Table
CREATE TABLE IF NOT EXISTS public."Heatwave_Prediction" (
    "Pre_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Station_ID" BIGINT NOT NULL REFERENCES public."Weather_Station"("Station_ID") ON DELETE CASCADE,
    "Pre_Temp" DECIMAL(5, 2) NOT NULL,
    "Target_Data" TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 day') NOT NULL,
    "Risk_level" VARCHAR(50) NOT NULL CHECK ("Risk_level" IN ('Safe', 'Low', 'Moderate', 'High', 'Extreme', 'Emergency')),
    "Confidence_Percent" DECIMAL(5, 2) NOT NULL CHECK ("Confidence_Percent" >= 0 AND "Confidence_Percent" <= 100)
);

-- 6. Alert Table
CREATE TABLE IF NOT EXISTS public."Alert" (
    "Alert_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Pre_ID" BIGINT REFERENCES public."Heatwave_Prediction"("Pre_ID") ON DELETE SET NULL,
    "Obs_ID" BIGINT REFERENCES public."Weather_Observation"("Obs_ID") ON DELETE SET NULL,
    "Alert_msg" TEXT NOT NULL,
    "Severity_level" VARCHAR(50) NOT NULL CHECK ("Severity_level" IN ('Safe', 'Low', 'Moderate', 'High', 'Extreme', 'Emergency')),
    "Status" VARCHAR(50) DEFAULT 'Active' CHECK ("Status" IN ('Active', 'Resolved', 'Dismissed'))
);

-- 7. User Table (Exact Relational Model Attributes)
CREATE TABLE IF NOT EXISTS public."User" (
    "User_ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "User_Name" VARCHAR(255) NOT NULL,
    "Email" VARCHAR(255) NOT NULL UNIQUE,
    "Phone_no" VARCHAR(50),
    "DOB" DATE,
    "Role" VARCHAR(50) DEFAULT 'user' CHECK ("Role" IN ('user', 'admin'))
);

-- Drop legacy auth constraint if present to allow automatic web application user sync
ALTER TABLE public."User" DROP CONSTRAINT IF EXISTS "User_User_ID_fkey";

-- 8. User_Feedback Table
CREATE TABLE IF NOT EXISTS public."User_Feedback" (
    "F_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "User_ID" UUID NOT NULL REFERENCES public."User"("User_ID") ON DELETE CASCADE,
    "F_Type" VARCHAR(100) NOT NULL,
    "Comments" TEXT NOT NULL,
    "Rating" INTEGER CHECK ("Rating" >= 1 AND "Rating" <= 5),
    "Submitted_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for optimal querying
CREATE INDEX IF NOT EXISTS idx_obs_station ON public."Weather_Observation"("Station_ID", "Recorded_At" DESC);
CREATE INDEX IF NOT EXISTS idx_prediction_station ON public."Heatwave_Prediction"("Station_ID", "Target_Data");
CREATE INDEX IF NOT EXISTS idx_alert_severity ON public."Alert"("Severity_level", "Status");

-- Enable Row Level Security (RLS)
ALTER TABLE public."Weather_Station" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Station_Location" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Weather_Observation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Report_Analysis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Heatwave_Prediction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Alert" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."User_Feedback" ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies before recreating to avoid duplicate errors
DROP POLICY IF EXISTS "Public read weather stations" ON public."Weather_Station";
DROP POLICY IF EXISTS "Public insert weather stations" ON public."Weather_Station";
DROP POLICY IF EXISTS "Public update weather stations" ON public."Weather_Station";
DROP POLICY IF EXISTS "Public read station locations" ON public."Station_Location";
DROP POLICY IF EXISTS "Public insert station locations" ON public."Station_Location";
DROP POLICY IF EXISTS "Public update station locations" ON public."Station_Location";
DROP POLICY IF EXISTS "Public delete station locations" ON public."Station_Location";
DROP POLICY IF EXISTS "Public read observations" ON public."Weather_Observation";
DROP POLICY IF EXISTS "Public read report analysis" ON public."Report_Analysis";
DROP POLICY IF EXISTS "Public read predictions" ON public."Heatwave_Prediction";
DROP POLICY IF EXISTS "Public read alerts" ON public."Alert";
DROP POLICY IF EXISTS "Public read user profiles" ON public."User";
DROP POLICY IF EXISTS "Public insert user profiles" ON public."User";
DROP POLICY IF EXISTS "Public update user profiles" ON public."User";
DROP POLICY IF EXISTS "Public insert feedback" ON public."User_Feedback";
DROP POLICY IF EXISTS "Public read feedback" ON public."User_Feedback";
DROP POLICY IF EXISTS "Admin full access stations" ON public."Weather_Station";
DROP POLICY IF EXISTS "Admin full access station locations" ON public."Station_Location";
DROP POLICY IF EXISTS "Admin full access observations" ON public."Weather_Observation";
DROP POLICY IF EXISTS "Admin full access predictions" ON public."Heatwave_Prediction";
DROP POLICY IF EXISTS "Admin full access alerts" ON public."Alert";
DROP POLICY IF EXISTS "Admin full access feedback" ON public."User_Feedback";

-- RLS Policies
CREATE POLICY "Public read weather stations" ON public."Weather_Station" FOR SELECT USING (true);
CREATE POLICY "Public insert weather stations" ON public."Weather_Station" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update weather stations" ON public."Weather_Station" FOR UPDATE USING (true);

CREATE POLICY "Public read station locations" ON public."Station_Location" FOR SELECT USING (true);
CREATE POLICY "Public insert station locations" ON public."Station_Location" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update station locations" ON public."Station_Location" FOR UPDATE USING (true);
CREATE POLICY "Public delete station locations" ON public."Station_Location" FOR DELETE USING (true);

CREATE POLICY "Public read observations" ON public."Weather_Observation" FOR SELECT USING (true);
CREATE POLICY "Public read report analysis" ON public."Report_Analysis" FOR SELECT USING (true);
CREATE POLICY "Public read predictions" ON public."Heatwave_Prediction" FOR SELECT USING (true);
CREATE POLICY "Public read alerts" ON public."Alert" FOR SELECT USING (true);

-- User table permissions
CREATE POLICY "Public read user profiles" ON public."User" FOR SELECT USING (true);
CREATE POLICY "Public insert user profiles" ON public."User" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update user profiles" ON public."User" FOR UPDATE USING (true);

-- User Feedback permissions
CREATE POLICY "Public insert feedback" ON public."User_Feedback" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read feedback" ON public."User_Feedback" FOR SELECT USING (true);

-- Admin Full Access Policy
CREATE POLICY "Admin full access stations" ON public."Weather_Station" FOR ALL USING (true);
CREATE POLICY "Admin full access station locations" ON public."Station_Location" FOR ALL USING (true);
CREATE POLICY "Admin full access observations" ON public."Weather_Observation" FOR ALL USING (true);
CREATE POLICY "Admin full access predictions" ON public."Heatwave_Prediction" FOR ALL USING (true);
CREATE POLICY "Admin full access alerts" ON public."Alert" FOR ALL USING (true);
CREATE POLICY "Admin full access feedback" ON public."User_Feedback" FOR ALL USING (true);

-- Seed Data: Indian Weather Stations
INSERT INTO public."Weather_Station" ("Station_ID", "Station_Code", "Station_Name", "Latitude", "Longitude", "Status")
VALUES 
    (1, 'ST-DEL-01', 'New Delhi Central Observatory', 28.6139, 77.2090, 'Active'),
    (2, 'ST-MUM-02', 'Mumbai Coastal Climate Station', 18.9220, 72.8347, 'Active'),
    (3, 'ST-KOL-03', 'Kolkata Alipore Observatory', 22.5326, 88.3278, 'Active'),
    (4, 'ST-CHE-04', 'Chennai Nungambakkam Post', 13.0604, 80.2496, 'Active'),
    (5, 'ST-BLR-05', 'Bengaluru Electronics City Unit', 12.9716, 77.5946, 'Active'),
    (6, 'ST-HYD-06', 'Hyderabad Begumpet Station', 17.4435, 78.4772, 'Active'),
    (7, 'ST-AHM-07', 'Ahmedabad Sabarmati Monitor', 23.0225, 72.5714, 'Active'),
    (8, 'ST-JAI-08', 'Jaipur Thar Fringe Observatory', 26.9124, 75.7873, 'Active')
ON CONFLICT ("Station_ID") DO NOTHING;

INSERT INTO public."Station_Location" ("Station_ID", "Location")
VALUES 
    (1, 'Connaught Place, New Delhi, Delhi NCR, India'),
    (2, 'Colaba Coastal Zone, Mumbai, Maharashtra, India'),
    (3, 'Alipore Climate Campus, Kolkata, West Bengal, India'),
    (4, 'Nungambakkam Urban Post, Chennai, Tamil Nadu, India'),
    (5, 'Electronic City Sector 1, Bengaluru, Karnataka, India'),
    (6, 'Begumpet Met Office, Hyderabad, Telangana, India'),
    (7, 'Sabarmati Riverfront, Ahmedabad, Gujarat, India'),
    (8, 'Pink City Substation, Jaipur, Rajasthan, India')
ON CONFLICT DO NOTHING;
